// lang.js — ANSI Niger — Traductions complètes

const translations = {
    fr: {
        tableau_bord: "Tableau de bord",
        stagiaires: "Stagiaires",
        visiteurs: "Visiteurs",
        employes: "Employés",
        agents_securite: "Agents de sécurité",
        pointage_stagiaires: "Pointage stagiaires",
        historique: "Historique",
        rapports: "Rapports",
        parametres: "Paramètres",
        mon_profil: "Mon profil",
        deconnexion: "Déconnexion",
        principal: "Principal",
        donnees: "Données",
        systeme: "Système",
        bonjour: "Bonjour,",
        bienvenue: "Bienvenue sur le système de gestion des entrées/sorties ANSI",
        total_enregistres: "Total enregistrés",
        visiteurs_aujourdhui: "Visiteurs aujourd'hui",
        nouveaux_visiteurs: "Nouveaux visiteurs",
        visiteurs_presents: "Visiteurs présents",
        en_ce_moment: "En ce moment",
        employes_ansi: "Employés ANSI",
        employes_enregistres: "Employés enregistrés",
        agents_actifs: "Agents actifs",
        visiteurs_7j: "Visiteurs — 7 derniers jours",
        statut_visites: "Statut des visites du jour",
        terminees: "Terminées",
        en_cours: "En cours",
        derniers_visiteurs: "Derniers visiteurs",
        sortie: "Sortie",
        termine: "Terminé",
        tous: "Tous",
        sortis: "Sortis",
        ajouter: "Ajouter",
        modifier: "Modifier",
        supprimer: "Supprimer",
        enregistrer: "Enregistrer",
        annuler: "Annuler",
        fermer: "Fermer",
        actualiser: "Actualiser",
        retour_dashboard: "Retour au Dashboard",
        rechercher: "Rechercher...",
        filtrer: "Filtrer",
        reset: "Reset",
        exporter: "Exporter",
        gestion_stagiaires: "Gestion des stagiaires",
        liste_stagiaires: "Liste des stagiaires",
        nouveau_stagiaire: "Nouveau stagiaire",
        total_stagiaires: "Total stagiaires",
        presents: "Présents",
        en_stage: "En stage",
        termines: "Terminés",
        nom: "Nom",
        prenom: "Prénom",
        email: "Email",
        telephone: "Téléphone",
        direction_stage: "Direction de stage",
        date_debut: "Date début",
        date_fin: "Date fin",
        statut: "Statut",
        actions: "Actions",
        actif: "En stage",
        detail_stagiaires: "Détail des stagiaires",
        nom_prenom: "Nom & Prénom",
        gestion_visiteurs: "Gestion des visiteurs",
        nouvelle_visite: "Nouvelle visite",
        enregistrer_entree: "Enregistrer l'entrée",
        mettre_a_jour: "Mettez à jour les informations",
        remplir_infos: "Remplissez les informations ci-dessous",
        modifier_visite: "Modifier la visite",
        n_piece: "N° pièce d'identité",
        structure: "Structure / Organisation",
        direction_visitee: "Direction visitée",
        personne_visitee: "Personne à rencontrer",
        entree: "Entrée",
        visiteurs_actifs: "Visiteurs actifs aujourd'hui",
        liste_visiteurs_actifs: "Liste des visiteurs actifs",
        corbeille: "Corbeille",
        en_cours_v: "En cours",
        total_aujourdhui: "Total aujourd'hui",
        present: "Présents",
        sortis_label: "Sortis",
        gestion_employes: "Gestion des employés",
        ajouter_employe: "Ajouter un employé",
        liste_employes: "Liste des employés",
        directions: "Directions",
        nouvelle_direction: "Nouvelle direction...",
        identite: "Identité",
        piece_contact: "Pièce & Contact",
        objet_visite: "Objet de la visite",
        poste: "Poste",
        gestion_securite: "Agents de sécurité",
        nouvel_agent: "Nouvel agent",
        liste_agents: "Liste des agents",
        total_agents: "Total agents",
        administrateurs: "Administrateurs",
        agents_sec: "Agents sécurité",
        login: "Login",
        role: "Rôle",
        cree_le: "Créé le",
        compte: "Compte",
        mot_de_passe: "Mot de passe",
        nouveau_mdp: "Nouveau mot de passe",
        mon_profil_titre: "Mon profil",
        informations_personnelles: "Informations personnelles",
        changer_mdp: "Changer le mot de passe",
        mdp_actuel: "Mot de passe actuel",
        confirmer_mdp: "Confirmer",
        sauvegarder: "Sauvegarder les informations",
        utilisateur_systeme: "Utilisé pour vous connecter au système",
        administrateur: "Administrateur",
        agent_securite: "Agent de sécurité",
        historique_visiteurs: "Historique visiteurs",
        pointages_stagiaires: "Pointages stagiaires",
        activites_systeme: "Activités système",
        total_visites: "Total visites",
        visites_aujourdhui: "Visites aujourd'hui",
        total_pointages: "Total pointages",
        pointages_aujourdhui: "Pointages aujourd'hui",
        total_activites: "Total activités",
        activites_aujourdhui: "Activités aujourd'hui",
        visiteur: "Visiteur",
        stagiaire: "Stagiaire",
        date: "Date",
        du: "Du",
        au: "Au",
        duree: "Durée",
        heure_entree: "Heure entrée",
        heure_sortie: "Heure sortie",
        enregistre_par: "Enregistré par",
        action: "Action",
        utilisateur: "Utilisateur",
        details: "Détails",
        ip: "IP",
        date_heure: "Date & Heure",
        statistiques: "Statistiques avancées",
        visiteurs_30j: "Visiteurs (30j)",
        nb_directions: "Directions",
        duree_moy: "Durée moy. (min)",
        taux_occupation: "Taux occupation",
        visiteurs_mois: "Visiteurs par mois",
        repartition_direction: "Répartition par direction",
        jours_affluence: "Jours de forte affluence",
        presents_7j: "Présents — 7 derniers jours",
        preferences: "Préférences générales",
        apparence: "Apparence",
        theme_sombre: "Thème sombre",
        theme_desc: "Basculer l'interface en mode nuit",
        langue_region: "Langue et région",
        langue_interface: "Langue de l'interface",
        langue_desc: "Choisissez la langue d'affichage",
        notifications_param: "Notifications",
        activer_notif: "Activer les notifications",
        activer_notif_desc: "Recevoir des alertes en temps réel",
        rappels: "Rappels quotidiens",
        rappels_desc: "Email récapitulatif des entrées/sorties du jour",
        donnees_param: "Données",
        retention: "Période de rétention des logs",
        retention_desc: "Durée de conservation des journaux d'activité",
        exporter_logs: "Exporter les logs",
        exporter_logs_desc: "Télécharger l'historique au format CSV",
        exporter_csv: "Exporter CSV",
        exporter_pdf: "Exporter PDF",
        enregistrer_params: "Enregistrer les modifications",
        pointage_jour: "Pointage du jour",
        stagiaires_actifs: "Stagiaires actifs",
        absent: "Absent",
        contact: "Contact",
        stage: "Stage",
        entree_btn: "Entrée",
        sortie_btn: "Sortie",
        connexion_titre: "Bienvenue 👋",
        connexion_sub: "Connectez-vous à votre espace de travail",
        identifiant: "Identifiant",
        se_connecter: "Se connecter",
        precedent: "Précédent",
        suivant: "Suivant",
        nom_famille: "Nom de famille",
        prenom_ph: "Prénom",
        mdp_actuel_ph: "Votre mot de passe actuel",
        mdp_min_ph: "Minimum 6 caractères",
        mdp_confirm_ph: "Confirmez le nouveau mot de passe",
        changer_mdp_btn: "Changer le mot de passe",
        entrez_mdp: "Entrez un nouveau mot de passe",
        pwd_tres_faible: "Très faible",
        pwd_faible: "Faible",
        pwd_moyen: "Moyen",
        pwd_fort: "Fort",
        pwd_tres_fort: "Très fort",
        footer_droits: "Tous droits réservés.",
        footer_version: "Système de gestion des entrées/sorties",
        aucun_visiteur: "Aucun visiteur",
        aucun_stagiaire: "Aucun stagiaire",
        aucun_employe: "Aucun employé",
        aucun_agent: "Aucun agent",
        restaurer: "Restaurer",
        rechercher_stagiaire: "Rechercher un stagiaire...",
        email_ph: "email@exemple.com",
        creer_compte: "Créer un nouveau compte d'accès",
        creer_agent: "Créer l'agent",
        resultats: "résultats",
        aucune_donnee: "Aucune donnée",
        aucun_pointage: "Aucun pointage",
        aucune_activite: "Aucune activité",
        toutes_actions: "Toutes les actions",
        rechercher_hist: "Nom, prénom, direction...",
        rechercher_details: "Détails, utilisateur...",
        mettre_a_jour_compte: "Mettez à jour vos informations de compte",
        renforcer_securite: "Renforcez la sécurité de votre compte",
        identifiant_ph: "Identifiant de connexion",
        stage_termine: "Stage terminé",
        mois_jan: "Jan", mois_fev: "Fév", mois_mar: "Mar", mois_avr: "Avr",
        mois_mai: "Mai", mois_juin: "Juin", mois_juil: "Juil", mois_aou: "Aoû",
        mois_sep: "Sep", mois_oct: "Oct", mois_nov: "Nov", mois_dec: "Déc",
        jour_lun: "Lun", jour_mar: "Mar", jour_mer: "Mer", jour_jeu: "Jeu",
        jour_ven: "Ven", jour_sam: "Sam", jour_dim: "Dim",
    },
    en: {
        tableau_bord: "Dashboard",
        stagiaires: "Trainees",
        visiteurs: "Visitors",
        employes: "Employees",
        agents_securite: "Security agents",
        pointage_stagiaires: "Trainee check-in",
        historique: "History",
        rapports: "Reports",
        parametres: "Settings",
        mon_profil: "My profile",
        deconnexion: "Logout",
        principal: "Main",
        donnees: "Data",
        systeme: "System",
        bonjour: "Hello,",
        bienvenue: "Welcome to the ANSI entry/exit management system",
        total_enregistres: "Total registered",
        visiteurs_aujourdhui: "Today's visitors",
        nouveaux_visiteurs: "New visitors",
        visiteurs_presents: "Visitors present",
        en_ce_moment: "Right now",
        employes_ansi: "ANSI employees",
        employes_enregistres: "Registered employees",
        agents_actifs: "Active agents",
        visiteurs_7j: "Visitors — last 7 days",
        statut_visites: "Today's visit status",
        terminees: "Completed",
        en_cours: "In progress",
        derniers_visiteurs: "Recent visitors",
        sortie: "Exit",
        termine: "Completed",
        tous: "All",
        sortis: "Exited",
        ajouter: "Add",
        modifier: "Edit",
        supprimer: "Delete",
        enregistrer: "Save",
        annuler: "Cancel",
        fermer: "Close",
        actualiser: "Refresh",
        retour_dashboard: "Back to Dashboard",
        rechercher: "Search...",
        filtrer: "Filter",
        reset: "Reset",
        exporter: "Export",
        gestion_stagiaires: "Trainee Management",
        liste_stagiaires: "Trainee list",
        nouveau_stagiaire: "New trainee",
        total_stagiaires: "Total trainees",
        presents: "Present",
        en_stage: "In training",
        termines: "Completed",
        nom: "Last name",
        prenom: "First name",
        email: "Email",
        telephone: "Phone",
        direction_stage: "Internship department",
        date_debut: "Start date",
        date_fin: "End date",
        statut: "Status",
        actions: "Actions",
        actif: "In training",
        detail_stagiaires: "Trainee details",
        nom_prenom: "Name & First name",
        gestion_visiteurs: "Visitor Management",
        nouvelle_visite: "New visit",
        enregistrer_entree: "Register entry",
        mettre_a_jour: "Update information",
        remplir_infos: "Fill in the information below",
        modifier_visite: "Edit visit",
        n_piece: "ID document number",
        structure: "Organization",
        direction_visitee: "Department visited",
        personne_visitee: "Person to meet",
        entree: "Entry",
        visiteurs_actifs: "Active visitors today",
        liste_visiteurs_actifs: "Active visitors list",
        corbeille: "Trash",
        en_cours_v: "In progress",
        total_aujourdhui: "Total today",
        present: "Present",
        sortis_label: "Exited",
        gestion_employes: "Employee Management",
        ajouter_employe: "Add employee",
        liste_employes: "Employee list",
        directions: "Departments",
        nouvelle_direction: "New department...",
        identite: "Identity",
        piece_contact: "ID & Contact",
        objet_visite: "Visit purpose",
        poste: "Position",
        gestion_securite: "Security agents",
        nouvel_agent: "New agent",
        liste_agents: "Agent list",
        total_agents: "Total agents",
        administrateurs: "Administrators",
        agents_sec: "Security agents",
        login: "Login",
        role: "Role",
        cree_le: "Created on",
        compte: "Account",
        mot_de_passe: "Password",
        nouveau_mdp: "New password",
        mon_profil_titre: "My profile",
        informations_personnelles: "Personal information",
        changer_mdp: "Change password",
        mdp_actuel: "Current password",
        confirmer_mdp: "Confirm",
        sauvegarder: "Save information",
        utilisateur_systeme: "Used to log into the system",
        administrateur: "Administrator",
        agent_securite: "Security agent",
        historique_visiteurs: "Visitor history",
        pointages_stagiaires: "Trainee check-ins",
        activites_systeme: "System activities",
        total_visites: "Total visits",
        visites_aujourdhui: "Visits today",
        total_pointages: "Total check-ins",
        pointages_aujourdhui: "Check-ins today",
        total_activites: "Total activities",
        activites_aujourdhui: "Activities today",
        visiteur: "Visitor",
        stagiaire: "Trainee",
        date: "Date",
        du: "From",
        au: "To",
        duree: "Duration",
        heure_entree: "Entry time",
        heure_sortie: "Exit time",
        enregistre_par: "Registered by",
        action: "Action",
        utilisateur: "User",
        details: "Details",
        ip: "IP",
        date_heure: "Date & Time",
        statistiques: "Advanced statistics",
        visiteurs_30j: "Visitors (30d)",
        nb_directions: "Departments",
        duree_moy: "Avg. duration (min)",
        taux_occupation: "Occupancy rate",
        visiteurs_mois: "Visitors per month",
        repartition_direction: "Distribution by department",
        jours_affluence: "Peak days",
        presents_7j: "Present — last 7 days",
        preferences: "General preferences",
        apparence: "Appearance",
        theme_sombre: "Dark theme",
        theme_desc: "Switch to night mode",
        langue_region: "Language & region",
        langue_interface: "Interface language",
        langue_desc: "Choose display language",
        notifications_param: "Notifications",
        activer_notif: "Enable notifications",
        activer_notif_desc: "Receive real-time alerts",
        rappels: "Daily reminders",
        rappels_desc: "Daily entry/exit summary email",
        donnees_param: "Data",
        retention: "Log retention period",
        retention_desc: "Duration of activity log storage",
        exporter_logs: "Export logs",
        exporter_logs_desc: "Download activity history as CSV",
        exporter_csv: "Export CSV",
        exporter_pdf: "Export PDF",
        enregistrer_params: "Save changes",
        pointage_jour: "Today's attendance",
        stagiaires_actifs: "Active trainees",
        absent: "Absent",
        contact: "Contact",
        stage: "Internship",
        entree_btn: "Entry",
        sortie_btn: "Exit",
        connexion_titre: "Welcome 👋",
        connexion_sub: "Log into your workspace",
        identifiant: "Username",
        se_connecter: "Log in",
        precedent: "Previous",
        suivant: "Next",
        nom_famille: "Last name",
        prenom_ph: "First name",
        mdp_actuel_ph: "Your current password",
        mdp_min_ph: "Minimum 6 characters",
        mdp_confirm_ph: "Confirm new password",
        changer_mdp_btn: "Change password",
        entrez_mdp: "Enter a new password",
        pwd_tres_faible: "Very weak",
        pwd_faible: "Weak",
        pwd_moyen: "Medium",
        pwd_fort: "Strong",
        pwd_tres_fort: "Very strong",
        footer_droits: "All rights reserved.",
        footer_version: "Entry/Exit Management System",
        aucun_visiteur: "No visitors",
        aucun_stagiaire: "No trainees",
        aucun_employe: "No employees",
        aucun_agent: "No agents",
        restaurer: "Restore",
        rechercher_stagiaire: "Search for a trainee...",
        email_ph: "email@example.com",
        creer_compte: "Create a new access account",
        creer_agent: "Create agent",
        resultats: "results",
        aucune_donnee: "No data",
        aucun_pointage: "No check-ins",
        aucune_activite: "No activity",
        toutes_actions: "All actions",
        rechercher_hist: "Name, first name, department...",
        rechercher_details: "Details, user...",
        mettre_a_jour_compte: "Update your account information",
        renforcer_securite: "Strengthen your account security",
        identifiant_ph: "Login identifier",
        stage_termine: "Internship completed",
        mois_jan: "Jan", mois_fev: "Feb", mois_mar: "Mar", mois_avr: "Apr",
        mois_mai: "May", mois_juin: "Jun", mois_juil: "Jul", mois_aou: "Aug",
        mois_sep: "Sep", mois_oct: "Oct", mois_nov: "Nov", mois_dec: "Dec",
        jour_lun: "Mon", jour_mar: "Tue", jour_mer: "Wed", jour_jeu: "Thu",
        jour_ven: "Fri", jour_sam: "Sat", jour_dim: "Sun",
    }
};

let currentLang = localStorage.getItem('langue') || 'fr';

function t(key) {
    return (translations[currentLang] && translations[currentLang][key]) ||
           (translations['fr'] && translations['fr'][key]) ||
           key;
}

function applyTranslations() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        const val = t(key);
        if (!val || val === key) return;
        const textNodes = Array.from(el.childNodes).filter(n => n.nodeType === Node.TEXT_NODE);
        if (textNodes.length > 0) {
            textNodes[0].textContent = val;
        } else if (el.children.length === 0) {
            el.textContent = val;
        }
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        const val = t(key);
        if (val && val !== key) el.placeholder = val;
    });
    document.querySelectorAll('[data-i18n-title]').forEach(el => {
        const key = el.getAttribute('data-i18n-title');
        const val = t(key);
        if (val && val !== key) el.title = val;
    });
    // Titre de la page
    const page = window.location.pathname.split('/').pop().replace('.html', '');
    const titleMap = {
        'dashboard': 'tableau_bord', 'stagiaires': 'stagiaires', 'visiteurs': 'visiteurs',
        'employes': 'employes', 'securite': 'agents_securite', 'accueil-agent': 'pointage_stagiaires',
        'historique': 'historique', 'rapports': 'rapports', 'parametres': 'parametres',
        'profil': 'mon_profil', 'index': 'connexion_titre'
    };
    if (titleMap[page]) {
        const titleEl = document.querySelector('title');
        if (titleEl) titleEl.textContent = t(titleMap[page]) + ' — ANSI';
    }
}

function setLanguage(lang) {
    if (!translations[lang]) lang = 'fr';
    currentLang = lang;
    localStorage.setItem('langue', lang);
    applyTranslations();
    window.dispatchEvent(new StorageEvent('storage', { key: 'langue', newValue: lang }));
}

// ❌ SUPPRIMÉ : document.addEventListener('DOMContentLoaded', () => applyTranslations());
// Chaque page appelle applyTranslations() dans son init() — pas besoin de double appel ici.

// Sync entre onglets
window.addEventListener('storage', e => {
    if (e.key === 'langue' && e.newValue && e.newValue !== currentLang) {
        currentLang = e.newValue;
        applyTranslations();
    }
});

window.t = t;
window.setLanguage = setLanguage;
window.applyTranslations = applyTranslations;